### PR TITLE
bizhawk: Initial linux makefile refactor

### PR DESCRIPTION
**Pull request by endrift**
Updates to get mGBA for BizHawk building on Linux. I have tested that it compiles but I haven't tested that it works. CC @yoshirulz

### CODE REVIEW

**Review by nattthebear — COMMENTED** [review]
LGTM

**Comment by YoshiRulz** [comment]
an hour of boring boilerplate later
Screenshot_20200726_123633

**Comment by vadosnaprimer** [comment]
Thank you!!! All I can do tho is just building and running it on widnows to make sure it still works, no review.

**Comment by endrift** [comment]
I already tested to make sure it still built on Windows, though I didn't confirm if the built dll works.

**Comment by YoshiRulz** [comment]
after submodule pull, Windows lib checked in at TASVideos/BizHawk@74f9a3db8, Hawk-side changes made at TASVideos/BizHawk@105250f60, and Linux lib checked in at TASVideos/BizHawk@2f5c947a5

**Pull request merged**
